Strings = {
	/*** flag ***/
	flag: 'images/de.png',
	cookie: 'de',
        /*** content ***/
        infoUrlAboutContent: 'http://aporee.org/maps/info/#content',
	/*** places ***/
	places: 'places',
	newLocationsDay: 'past 24 hours',
	newLocationsWeek: 'past week',
	newLocationsMonth: 'past month',
	getFavourites: 'listener\'s favourites this month',
	playProjects: 'user projects',
	// projects
	listProjects: ' - project maps, order by ',
	overviewProjects: 'overview of project maps',
	orderProjectsDate: 'last changed',
	orderProjectsTitle: 'title',
	by: 'by',
	/*** play ***/
	play: 'play',
	playRandom: 'random sequence',
	playVisible: 'currently visible',
	/*** search ***/
	search: 'search',
	searchGoogle: 'places (google)',
	searchGoogleInput: 'your search here...',
	searchGoogleNoResult: 'no places found...',
	searchMaps: 'radio aporee sounds',
	searchExtended: 'extendend...',
	searchUserResult: 'latest sounds by',
	searchUserNoResult: 'no sounds for',
	searchLocationInput: 'search sounds and places in radio aporee',
	searchLocationResult: 'found:',
	searchLocationNoResult: 'no places found',
	/*** tools ***/
	tools: 'tools',
	toolsCurrentMap: 'share visible map',
	toolsLinkCurrentMap: 'to create a link to the currently visible map, copy the following code to your webpage:',
	toolsBookmarkCurrentMap: 'or bookmark this link (right click):',
	toolsMailCurrentMap: 'or send it <b>per email</b>',
	toolsSelectMap: 'map selection',
	selectMap: '<p>press &lt;shift&gt; and drag/select the desired area on the map',
	toolsExportSelectedMap: 'to create a map of the selected area, copy the following code to your webpage:',
	/*** about ***/
	about: 'about...',
	help: 'info &amp; help',
	stats: 'statistics',
	projects: 'other projects',
	/*** lists ***/
	playList: 'play all',
	/*** soundInfo ***/
	details: 'more details',
	/* stats */
	statsPlaces: 'places',
	statsSounds: 'sounds',
	statsLength: 'total',
	statsAverage: '&empty;',
	statsUser: 'contributors',
	/* center */
	centerDescr: 'geographical center of all locations',
	/* infowindow */
	downloadSound: 'download sound',
	sendComment: 'send a comment to the author:',
	yourEmail: "your email (optional, won't be saved):",
	submitComment: 'send',
	addRecording: 'add recording',
	embedMap: 'share &amp; embed',
	mixMode: 'open geo mixer',
	toolTipMixMode: 'open this place in geo mixer mode.',
	toolTipAddRecording: 'add a recording to this place instead of creating a new one. sounds will play consecutively.',
	toolTipEmbed: 'embed, or share a map of this location on your blog or website, see also <i>tools</i> for more options.',
	embedCurrentLocation: 'to create a map of the current Location, copy the following code to your webpage:',
	linkCurrentLocation: 'to create a link to the current location, copy the following code to your webpage:',
	favouritesAdd: 'choose this location as one of your favourites of the month',
	favouritesError: 'error: could not add location to favourites.',
	favouritesOK: 'location added to favourites of the month!',
	favouritesExists: 'you have already added this location to your favourites.',
	moreDetails: 'more details...',
	/* upload */
	uploadNewTitle: 'add a new location',
	uploadToTitle: 'add a recording to this location',
	uploadAboutContent: 'respect the rules, read this before posting!',
	uploadPlaceTitle: 'address, placename, title etc.:',
	uploadRecTitle: 'title of recording:',
	uploadRecDate: 'recording date (y-m-d)/ time:',
	uploadDescription: 'description (please provide details about place, recording, situation, techniques etc.):',
	uploadEmail: 'your email address:',
	uploadLicence: 'licence (<a target="_blank" href="http://creativecommons.org/licenses/">info...</a>):',
	uploadFile: 'choose file (mp3 or wav):',
	uploadUrl: 'or: download sound from URL:',
	uploadSend: 'send',
	uploadCancel: 'cancel',
	uploadValidateError: 'error! please check:\n\n',
	uploadValidatePlaceTitle: 'address, placename\n',
	uploadValidateRecTitle: 'title of recording\n',
	uploadValidateEmail: 'email address\n',
	uploadValidateUrl: 'download url\n',
	uploadValidateTime: 'recording date\n',
	uploadUploading: '<img src="images/loading.gif"> uploading to aporee...',
	/* errors */
	uploadSuccess: 'upload successful, confirmation email has been sent.',
	uploadError1: 'upload failed, your file probably exceeds the max. size of 100mb.',
	uploadError2: 'upload failed, your file exceeds the max. size of 100mb.',
	uploadError3: 'upload failed, your file was not send completely, please try again.',
	uploadError4: 'upload failed, no file or url selected.',
	uploadError5: 'download failed, could not access remote soundfile.',
	uploadError6: 'download failed, could not transfer remote soundfile.',
	uploadError7: 'upload failed, your file has the wrong extension and/or format.  respect the posting rules, see http://aporee.org/maps/info#content',
	uploadError8: 'upload failed, your file has the wrong format. respect the posting rules, see http://aporee.org/maps/info#content',
	uploadErrorOther: 'upload failed, an unknown error occured, radio aporee has been informed.'
};
